// oxlint-disable no-console
/**
 * Regenerates `src/generated.ts` from the SVG files in `src/assets`.
 *
 * onyx solves this with a virtual module produced by its own vite plugin; here
 * the file is generated and committed instead, so `tsc --noEmit` and editor
 * go-to-definition work on a fresh clone without a build step first.
 *
 * Every icon is exported as its raw SVG markup (a `string`), loaded through
 * Vite's `?raw` suffix so the markup lives in exactly one place — the .svg file.
 *
 * Run with: pnpm --filter @okryshto/icons generate
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join } from "node:path";

const src = fileURLToPath(new URL("../src", import.meta.url));

/** `"arrow-up-right.svg"` → `"iconArrowUpRight"` (mirrors utils.ts). */
const getIconImportName = (iconName) =>
  `icon${iconName
    .replace(/\.svg$/, "")
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join("")}`;

const files = readdirSync(join(src, "assets"))
  .filter((file) => file.endsWith(".svg"))
  .sort();

if (files.length === 0) throw new Error("no SVG files found in src/assets");

const metadata = JSON.parse(readFileSync(join(src, "metadata.json"), "utf8"));
const missing = files.map((f) => f.replace(/\.svg$/, "")).filter((name) => !(name in metadata));
if (missing.length > 0) {
  throw new Error(`missing src/metadata.json entries for: ${missing.join(", ")}`);
}
const orphaned = Object.keys(metadata).filter((name) => !files.includes(`${name}.svg`));
if (orphaned.length > 0) {
  throw new Error(`src/metadata.json describes icons with no SVG file: ${orphaned.join(", ")}`);
}

const lines = files.flatMap((file) => {
  const local = `raw${getIconImportName(file).slice(4)}`;
  return [
    `import ${local} from "./assets/${file}?raw";`,
    // The explicit `: string` keeps the `?raw` specifier out of the emitted
    // .d.ts — consumers must not have to resolve a Vite-only import suffix.
    `export const ${getIconImportName(file)}: string = ${local};`,
  ];
});

const banner = [
  "// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.",
  "// Add or remove an SVG in src/assets, update src/metadata.json, then run:",
  "//   pnpm --filter @okryshto/icons generate",
  "",
].join("\n");

writeFileSync(join(src, "generated.ts"), `${banner}${lines.join("\n")}\n`);
console.log(`[@okryshto/icons] generated ${files.length} icon exports → src/generated.ts`);
